[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "python-escpos"
dynamic = ["version"]
description = "Python library to manipulate ESC/POS Printers"
readme = "README.rst"
license = {text = "MIT"}
authors = [
    {name = "python-escpos developers", email = "dev@pkanzler.de"},
]
maintainers = [
    {name = "Patrick Kanzler", email = "dev@pkanzler.de"},
]
keywords = [
    "ESC/POS",
    "printer",
    "printing",
    "receipt",
    "thermoprinter",
    "voucher",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Office/Business :: Financial :: Point-Of-Sale",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8"
dependencies = [
    "argcomplete",
    "importlib_resources",
    "Pillow>=2.0",
    "platformdirs",
    "python-barcode>=0.15.0,<1",
    "PyYAML",
    "qrcode>=4.0",
    "setuptools",
    "six",
]


[project.optional-dependencies]
all = [
    "pycups; platform_system!='Windows'",
    "pyserial",
    "pyusb>=1.0.0",
    "pywin32; platform_system=='Windows'",
]
cups = [
    "pycups; platform_system!='Windows'",
]
serial = [
    "pyserial",
]
usb = [
    "pyusb>=1.0.0",
]
win32 = [
    "pywin32; platform_system=='Windows'",
]


[project.scripts]
python-escpos = "escpos.cli:main"


[project.urls]
"Bug Tracker" = "https://github.com/python-escpos/python-escpos/issues"
Documentation = "https://python-escpos.readthedocs.io/en/latest/"
Homepage = "https://github.com/python-escpos/python-escpos"
"Release Notes" = "https://github.com/python-escpos/python-escpos/releases"


[tool.setuptools_scm]
version_file = "src/escpos/version.py"
version_file_template = """\
#!/usr/bin/python
#  -*- coding: utf-8 -*-
\"\"\"Version identifier.

file generated by setuptools_scm
don't change, don't track in version control
\"\"\"

version = '{version}'
"""


[tool.black]
extend-exclude = 'capabilities-data'


[tool.isort]
profile = "black"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --cov escpos --cov-report=xml"
testpaths = ["test", "src", "src/escpos", "escpos"]



[[tool.mypy.overrides]]
module = [
  "pytest",
  "jaconv",
  "scripttest",
  "barcode.*",
  "qrcode",
  "usb.*",
  "cups",
  "win32print",
]
ignore_missing_imports = true


[tool.tox]
requires = ["tox>=4.11"]
envlist = ["3.9", "3.10", "3.11", "3.12", "3.13", "docs", "flake8", "mypy"]


[tool.tox.gh.python]
"3.13" = ["3.13"]
"3.12" = ["3.12"]
"3.11" = ["3.11"]
"3.10" = ["3.10"]
"3.9" = ["3.9"]


[tool.tox.env_run_base]
deps = [
  "jaconv",
  "coverage",
  "scripttest",
  "mock",
  "pytest>=7.4",
  "pytest-cov",
  "pytest-mock",
  "hypothesis>=6.83",
  "python-barcode>=0.15.0,<1",
]
extras = ["all"]
commands = [["pytest"]]
passenv = [
  "ESCPOS_CAPABILITIES_PICKLE_DIR",
  "ESCPOS_CAPABILITIES_FILE",
  "CI",
  "TRAVIS",
  "TRAVIS_*",
  "APPVEYOR",
  "APPVEYOR_*",
  "CODECOV_*",
]
setenv = { PY_IGNORE_IMPORTMISMATCH = "1" }


[tool.tox.env.docs]
base_python = ["python"]
changedir = "doc"
deps = [
  "sphinx>=7.2.3",
  "setuptools_scm",
  "python-barcode>=0.15.0,<1",
  "sphinx-argparse",
  "sphinxcontrib-spelling>=8.0.0",
  "sphinxcontrib.datatemplates",
  "sphinx-autodoc-typehints",
  "sphinx_rtd_theme",
  "pycups",
]
commands = [
  [
    "sphinx-build",
    "-W",
    "-b",
    "html",
    "-d",
    "{envtmpdir}/doctrees",
    ".",
    "{envtmpdir}/html",
  ],
  [
    "sphinx-build",
    "-W",
    "-b",
    "spelling",
    "-d",
    "{envtmpdir}/doctrees",
    ".",
    "{envtmpdir}/spelling",
  ],
]


[tool.tox.env.flake8]
base_python = ["python"]
deps = ["flake8", "flake8-docstrings"]
commands = [["flake8"]]


[tool.tox.env.mypy]
base_python = ["python"]
deps = [
  "mypy",
  "types-six",
  "types-mock",
  "types-PyYAML",
  "types-Pillow",
  "types-pyserial",
  "types-pywin32>=306.0.0.6",
  "types-flask",
  "hypothesis>=6.83",
  "jaconv",
]
commands = [["mypy", "src", "test", "examples"]]


[tool.coverage.run]
branch = true
