name: Style

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Ruff
        uses: astral-sh/ruff-action@v3
      - name: Ruff check
        run: ruff check --fix --output-format=github
      - name: Ruff format
        run: ruff format
